class PieceOfContent(object):
    def __init__(self, **kwargs):
        self.path = kwargs.get("path", None)
        self.contentLibraryName = kwargs.get("contentLibraryName", None)
        self.authoringTemplateName = kwargs.get("authoringTemplateName", None)
        self.name = kwargs.get("name", None)
        self.title = kwargs.get("title", None)
        self.approvers = kwargs.get("approvers", None)
        self.categories = kwargs.get("categories", None)
        self.description = kwargs.get("description", None)
        self.creationDate = kwargs.get("creationDate", None)
        self.expiryDate = kwargs.get("expiryDate", None)
        self.generalDateOne = kwargs.get("generalDateOne", None)
        self.generalDateTwo = kwargs.get("generalDateTwo", None)
        self.keywords = kwargs.get("keywords", None)
        self.owners = kwargs.get("owners", None)
        self.authors = kwargs.get("authors", None)
        self.effectiveDate = kwargs.get("effectiveDate", None)
